# Generated by Django 4.0.6 on 2022-12-09 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default='21d12d1f', editable=False, primary_key=True, serialize=False)),
                ('casttype', models.IntegerField(choices=[(1, 'インスタントウィン'), (2, '後日抽選')], verbose_name='抽選方式')),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('sdate', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('edate', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('instancewin', models.IntegerField(default=0)),
                ('missing_img', models.ImageField(blank=True, null=True, upload_to='missing_images')),
                ('is_publish', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date At')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('action_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='gift_files')),
                ('codetype', models.CharField(max_length=40, verbose_name='コードタイプ')),
                ('candidate_num', models.IntegerField(default=1, verbose_name='当選者数')),
                ('color', models.CharField(max_length=6, verbose_name='ギフトカラー')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='受取期限')),
                ('sdate', models.DateTimeField(blank=True, null=True, verbose_name='有効期間/開始')),
                ('edate', models.DateTimeField(blank=True, null=True, verbose_name='有効期間/終了')),
                ('detail', models.URLField(blank=True, null=True, verbose_name='詳細URL')),
                ('money', models.IntegerField(default=0, verbose_name='ギフト金額')),
                ('useterm_doc', models.TextField()),
                ('attention_doc', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='creative_files')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('retweet_url', models.URLField(blank=True, null=True)),
                ('tweet_title', models.TextField(blank=True, max_length=256, null=True)),
                ('tweet_img', models.ImageField(blank=True, null=True, upload_to='tweet_images')),
                ('campaign_url', models.BooleanField(default=False)),
                ('action_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.twitteraction')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_status', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
