# Generated by Django 4.0.6 on 2022-12-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.UUIDField(default='72a842f7', editable=False, primary_key=True, serialize=False),
        ),
    ]
