# Generated by Django 4.0.6 on 2022-12-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.UUIDField(default='9afa19e2', editable=False, primary_key=True, serialize=False),
        ),
    ]
