# Generated by Django 4.0.6 on 2022-12-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.UUIDField(default='f87a5b35', editable=False, primary_key=True, serialize=False),
        ),
    ]
