# Generated by Django 4.0.6 on 2022-12-09 03:28

import dashboard.models
from django.db import migrations
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=dashboard.models.ULIDField(default=ulid.api.api.Api.new, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
