# Generated by Django 4.0.6 on 2022-12-09 09:07

import dashboard.models
from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraction',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=dashboard.models.ULIDField(default=ulid.api.api.Api.new, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
