# Generated by Django 4.0.6 on 2022-12-09 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_type', models.CharField(blank=True, max_length=26, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='username')),
                ('avatar', models.ImageField(upload_to='user_avatars')),
                ('email_notification', models.BooleanField(default=True, verbose_name='メール設定')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date At')),
                ('created_by', models.CharField(blank=True, max_length=26, null=True, verbose_name='Created Person By')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date At')),
                ('updated_by', models.CharField(blank=True, max_length=26, null=True, verbose_name='Updated Person By')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted Date At')),
                ('deleted_by', models.CharField(blank=True, max_length=26, null=True, verbose_name='Deleted Person By')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=255)),
                ('oauth_token_secret', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=55)),
                ('screen_name', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=55)),
                ('profile_image_url', models.CharField(max_length=255, null=True)),
                ('is_notified', models.BooleanField(default=False, verbose_name='Is notified?')),
                ('twitter_oauth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.twitterauthtoken')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='キャンペーン主催者名')),
                ('account_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ユーザー名')),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ブランド名')),
                ('profile_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='ブランドURL')),
                ('header_img', models.ImageField(upload_to='header_imgs', verbose_name='ヘッダー画像')),
                ('contact_form', models.URLField(blank=True, max_length=255, null=True, verbose_name='キャンペーンお問い合わせ先')),
                ('contact_form_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
